### PR TITLE
added screen name in getAccessToken method

### PR DESCRIPTION
**Pull request by sivaram636**

### CODE REVIEW

**Review by Nargonath — CHANGES_REQUESTED** [review]
Thanks for your contribution. One thing though, the `dist` folder is supposed to be ignored as it is added to the `.gitignore` file. How did you manage to track them to the repo? Please remove them.

**Comment by sivaram636** [comment]
@Nargonath Have removed the dist files.

**Review by sivaram636 — COMMENTED** [review]
Have removed the dist folder. Please do merge the PR.

**Review by Nargonath — APPROVED** [review]

**Comment by sivaram636** [comment]
@Nargonath When will this be released?

**Comment by Nargonath** [comment]
It should have been automatically released but there was a problem with the NPM token in the CI process. Fixed it, `v1.1.0` is released: https://github.com/Nargonath/twitter-auth-await/releases/tag/v1.1.0

**Pull request merged**
